import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        dashboard: "Dashboard",
        rentTractor: "Rent a Tractor",
        services: "Rural Services",
        aiScan: "AI Crop Scan",
        chatbot: "Govt Buddy AI",
        wallet: "My Wallet",
        admin: "Admin Hub",
        providerHub: "Provider Hub",
        logout: "Logout",
        welcome: "Welcome back",
        recentActivities: "Recent Activities",
        notifications: "Notifications",
        upgrade: "Upgrade Hub",
        searchPlaceholder: "Search services, tractors...",
        odisha: "Odisha, India",
        emergency: "Emergency SOS",
        hireNow: "Hire Now",
        bookNow: "Book Now",
        eta: "ETA",
        total: "Total",
        logistics: "Agri Logistics",
        agriMarket: "Agri Market",
        allCategories: "All Categories",
        fertilizers: "Fertilizers",
        seeds: "Seeds",
        pesticides: "Pesticides",
        insecticides: "Insecticides",
        machinery: "Machinery",
        tools: "Tools",
        addToCart: "Add to Cart",
        buyNow: "Buy Now",
        cartTotal: "Cart Total",
        proceedToCheckout: "Proceed to Checkout",
        deliveryAddress: "Delivery Address",
        paymentHub: "Payment Hub",
        orderSuccess: "Order Placed Successfully",
        downloadReceipt: "Download Receipt",
        landLease: "Land Lease & Rent",
        listLand: "List Your Land",
        findLand: "Find land for your next crop",
        searchLocation: "Search by location...",
        acres: "Acres",
        perMonth: "per Month",
        viewDetails: "View Details",
        owner: "Owner",
        soilType: "Soil Type",
        leaseDuration: "Lease Duration",
        months: "Months",
        proceedToLease: "Proceed to Lease",
        agreement: "Lease Agreement",
    },
    or: {
        dashboard: "ଡ୍ୟାସବୋର୍ଡ",
        rentTractor: "ଟ୍ରାକ୍ଟର ଭଡା",
        services: "ଗ୍ରାମୀଣ ସେବା",
        aiScan: "AI ଶସ୍ୟ ସ୍କାନ",
        chatbot: "ସରକାରୀ ବନ୍ଧୁ AI",
        wallet: "ମୋ ୱାଲେଟ୍",
        admin: "ଆଡମିନ୍ ହବ୍",
        providerHub: "ପ୍ରଦାନକାରୀ ହବ୍",
        logout: "ଲଗ୍ ଆଉଟ୍",
        welcome: "ସ୍ୱାଗତମ୍",
        recentActivities: "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",
        notifications: "ସୂଚନା",
        upgrade: "ଅପଗ୍ରେଡ୍ ହବ୍",
        searchPlaceholder: "ସେବା, ଟ୍ରାକ୍ଟର ଖୋଜନ୍ତୁ...",
        odisha: "ଓଡ଼ିଶା, ଭାରତ",
        emergency: "ଜରୁରୀକାଳୀନ ସେବା",
        hireNow: "ନିଯୁକ୍ତି କରନ୍ତୁ",
        bookNow: "ବୁକିଂ କରନ୍ତୁ",
        eta: "ଆସିବା ସମୟ",
        total: "ମୋଟ୍",
        logistics: "କୃଷି ପରିବହନ",
        agriMarket: "କୃଷି ବଜାର",
        allCategories: "ସମସ୍ତ ଶ୍ରେଣୀ",
        fertilizers: "ସାର",
        seeds: "ବିହନ",
        pesticides: "କୀଟନାଶକ",
        insecticides: "ପୋକମରା ଔଷଧ",
        machinery: "ଯନ୍ତ୍ରପାତି",
        tools: "ଉପକରଣ",
        addToCart: "କାର୍ଟରେ ଯୋଡନ୍ତୁ",
        buyNow: "ଏବେ କିଣନ୍ତୁ",
        cartTotal: "ମୋଟ୍ ମୂଲ୍ୟ",
        proceedToCheckout: "ଆଗକୁ ବଢନ୍ତୁ",
        deliveryAddress: "ବିତରଣ ଠିକଣା",
        paymentHub: "ପେମେଣ୍ଟ ହବ୍",
        orderSuccess: "ଅର୍ଡର ସଫଳ ହେଲା",
        downloadReceipt: "ରସିଦ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
        landLease: "ଜମି ଲିଜ୍ ଏବଂ ଭଡା",
        listLand: "ଆପଣଙ୍କ ଜମି ତାଲିକାଭୁକ୍ତ କରନ୍ତୁ",
        findLand: "ଆପଣଙ୍କ ପରବର୍ତ୍ତୀ ଚାଷ ପାଇଁ ଜମି ଖୋଜନ୍ତୁ",
        searchLocation: "ସ୍ଥାନ ଅନୁସାରେ ଖୋଜନ୍ତୁ...",
        acres: "ଏକର",
        perMonth: "ମାସିକ",
        viewDetails: "ବିବରଣୀ ଦେଖନ୍ତୁ",
        owner: "ମାଲିକ",
        soilType: "ମାଟିର ପ୍ରକାର",
        leaseDuration: "ଲିଜ୍ ଅବଧି",
        months: "ମାସ",
        proceedToLease: "ଲିଜ୍ ପାଇଁ ଆଗକୁ ବଢନ୍ତୁ",
        agreement: "ଲିଜ୍ ଚୁକ୍ତିନାମା",
    },
    hi: {
        dashboard: "डैशबोर्ड",
        rentTractor: "ट्रैक्टर किराये पर लें",
        services: "ग्रामीण सेवाएं",
        aiScan: "AI फसल स्कैन",
        chatbot: "सरकारी साथी AI",
        wallet: "मेरा वॉलेट",
        admin: "एडमिन हब",
        providerHub: "प्रदाता हब",
        logout: "लॉग आउट",
        welcome: "स्वागत है",
        recentActivities: "हाल की गतिविधियां",
        notifications: "सूचनाएं",
        upgrade: "अपग्रेड हब",
        searchPlaceholder: "सेवाएं, ट्रैक्टर खोजें...",
        odisha: "ओडिशा, भारत",
        emergency: "आपातकालीन सेवा",
        hireNow: "अभी बुक करें",
        bookNow: "बुक करें",
        eta: "आगमन समय",
        total: "कुल",
        logistics: "कृषि परिवहन",
        agriMarket: "कृषि बाजार",
        allCategories: "सभी श्रेणियां",
        fertilizers: "खाद",
        seeds: "बीज",
        pesticides: "कीटनाशक",
        insecticides: "कीट नियंत्रण",
        machinery: "मशीनरी",
        tools: "उपकरण",
        addToCart: "कार्ट में जोड़ें",
        buyNow: "अभी खरीदें",
        cartTotal: "कुल मूल्य",
        proceedToCheckout: "चेक-आउट करें",
        deliveryAddress: "डिलीवरी का पता",
        paymentHub: "भुगतान केंद्र",
        orderSuccess: "ऑर्डर सफलतापूर्वक संपन्न",
        downloadReceipt: "रसीद डाउनलोड करें",
        landLease: "भूमि पट्टा और किराया",
        listLand: "अपनी भूमि सूचीबद्ध करें",
        findLand: "अपनी अगली फसल के लिए भूमि खोजें",
        searchLocation: "स्थान से खोजें...",
        acres: "एकड़",
        perMonth: "प्रति माह",
        viewDetails: "विवरण देखें",
        owner: "मालिक",
        soilType: "मिट्टी का प्रकार",
        leaseDuration: "पट्टा अवधि",
        months: "महीने",
        proceedToLease: "पट्टे के लिए आगे बढ़ें",
        agreement: "पट्टा समझौता",
    },
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('gramai_lang') || 'en');

    useEffect(() => {
        localStorage.setItem('gramai_lang', lang);
    }, [lang]);

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
